# Generated by Django 5.2 on 2025-05-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_client_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_sum',
            field=models.FloatField(default='0', verbose_name='сумма контракта'),
        ),
    ]
