# Generated by Django 5.2 on 2025-05-02 14:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bank', '0001_initial'),
        ('service', '0007_alter_servicesclientmonthlyinvoice_operations_add_all_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('data', models.DateField(verbose_name='Дата добавления вручную')),
                ('amount', models.PositiveIntegerField(default='0', verbose_name='Сумма')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('type_operation', models.CharField(choices=[('entry', 'entry'), ('out', 'out')], default='out', max_length=5)),
                ('meta_categ', models.CharField(choices=[('oper_account', 'oper_account'), ('banking', 'banking'), ('nalog', 'nalog'), ('salary', 'salary'), ('suborders', 'suborders'), ('entrering', 'entrering'), ('none', 'none')], default='none', max_length=20)),
                ('bank_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_in', to='bank.bank', verbose_name='банк конечный назначения операции')),
                ('bank_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_to', to='bank.bank', verbose_name='банк конечный назначения операции')),
                ('monthly_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='service.servicesclientmonthlyinvoice', verbose_name='Счет за цслугу')),
            ],
        ),
    ]
