# Generated by Django 5.2 on 2025-05-05 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_alter_operation_bank_in'),
        ('service', '0011_subcontractmonth_category_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='suborder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='service.subcontractmonth', verbose_name='Субподряд для оплат'),
        ),
    ]
