# Generated by Django 5.2 on 2025-05-06 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_groupeoperaccount'),
        ('operation', '0004_alter_operation_options_alter_operation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='operaccount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bank.groupeoperaccount', verbose_name='По оперсчету'),
        ),
    ]
