# Generated by Django 5.2 on 2025-05-08 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_groupesalary'),
        ('operation', '0005_operation_operaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bank.groupesalary', verbose_name='По зарплатам'),
        ),
    ]
