# Generated by Django 5.2 on 2025-05-09 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employeeincategory_options'),
        ('operation', '0006_operation_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employee.employee', verbose_name='Сотрудник'),
        ),
    ]
