# Generated by Django 5.2 on 2025-05-29 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_categnalog'),
        ('operation', '0007_operation_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='nalog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bank.categnalog', verbose_name='Налоги'),
        ),
    ]
