# Generated by Django 5.2 on 2025-06-06 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_operation_nalog'),
        ('service', '0020_subcontractothercategory_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='suborder_other',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='service.subcontractothercategory', verbose_name='Другие субконтракты без привязке в услуге'),
        ),
    ]
