# Generated by Django 5.2 on 2025-06-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_operation_between_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='update_timestamp',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
