# Generated by Django 5.2 on 2025-04-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_servicesclientmonthlyinvoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesclientmonthlyinvoice',
            name='diff_sum',
            field=models.PositiveIntegerField(default='0', verbose_name='сумма для распределения по скбподряду адв'),
        ),
    ]
