# Generated by Django 5.2 on 2025-04-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_servicesclientmonthlyinvoice_diff_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_add_all',
            field=models.PositiveIntegerField(blank=True, default='0', null=True, verbose_name='Сумма прихода вся'),
        ),
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_add_ip',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Сумма прихода ИП'),
        ),
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_add_nal',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Сумма прихода нал'),
        ),
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_add_ооо',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Сумма прихода ООО'),
        ),
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_out_all',
            field=models.PositiveIntegerField(blank=True, default='0', null=True, verbose_name='Сумма расхода вся'),
        ),
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_out_ip',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Сумма расхода ИП'),
        ),
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_out_nal',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Сумма расхода нал'),
        ),
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_out_ооо',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Сумма расхода ООО'),
        ),
    ]
