# Generated by Django 5.2 on 2025-05-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_alter_servicesclientmonthlyinvoice_operations_add_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_add_diff_all',
            field=models.PositiveIntegerField(blank=True, default='0', null=True, verbose_name='Сумма прихода остаток'),
        ),
        migrations.AddField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_out_diff_all',
            field=models.PositiveIntegerField(blank=True, default='0', null=True, verbose_name='Сумма прихода остаток'),
        ),
    ]
