# Generated by Django 5.2 on 2025-05-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_servicesclientmonthlyinvoice_operations_add_diff_all_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='название площадки')),
            ],
        ),
    ]
