# Generated by Django 5.2 on 2025-05-03 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employeeincategory_options'),
        ('service', '0009_advplatform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advplatform',
            options={'verbose_name': 'Рекламная площадка', 'verbose_name_plural': 'Рекламные площадки'},
        ),
        migrations.AlterField(
            model_name='advplatform',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название площадки'),
        ),
        migrations.CreateModel(
            name='SubcontractMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateField(auto_now_add=True, verbose_name='Дата добавления')),
                ('amount', models.PositiveIntegerField(default='0', verbose_name='сумма субподряд')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.employee', verbose_name='Сотрудник')),
                ('month_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.servicesclientmonthlyinvoice')),
                ('platform', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service.advplatform', verbose_name='Рекламная площадка')),
            ],
        ),
    ]
