# Generated by Django 5.2 on 2025-05-03 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employeeincategory_options'),
        ('service', '0010_alter_advplatform_options_alter_advplatform_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractmonth',
            name='category_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.categoryemployee', verbose_name='Отдел'),
        ),
    ]
