# Generated by Django 5.2 on 2025-05-06 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_subcontractmonth_category_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='adv_all_sum',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Сумма ведения для ADV'),
        ),
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='contract_sum',
            field=models.FloatField(default='0', verbose_name='Сумма контракта'),
        ),
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='diff_sum',
            field=models.FloatField(default='0', verbose_name='сумма для распределения по скбподряду адв'),
        ),
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_add_all',
            field=models.FloatField(blank=True, default='0', null=True, verbose_name='Сумма прихода вся'),
        ),
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_add_diff_all',
            field=models.FloatField(blank=True, default='0', null=True, verbose_name='Сумма прихода остаток'),
        ),
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_add_ip',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Сумма прихода ИП'),
        ),
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_add_nal',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Сумма прихода нал'),
        ),
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_add_ооо',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Сумма прихода ООО'),
        ),
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_out_all',
            field=models.FloatField(blank=True, default='0', null=True, verbose_name='Сумма расхода вся'),
        ),
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_out_diff_all',
            field=models.FloatField(blank=True, default='0', null=True, verbose_name='Сумма прихода остаток'),
        ),
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_out_ip',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Сумма расхода ИП'),
        ),
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_out_nal',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Сумма расхода нал'),
        ),
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_out_ооо',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Сумма расхода ООО'),
        ),
        migrations.AlterField(
            model_name='subcontractmonth',
            name='amount',
            field=models.FloatField(default='0', verbose_name='сумма субподряд'),
        ),
    ]
