# Generated by Django 5.2 on 2025-05-15 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_alter_servicesclientmonthlyinvoice_adv_all_sum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='month',
            field=models.DateField(verbose_name='Месяц'),
        ),
    ]
