# Generated by Django 5.2 on 2025-05-15 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_alter_servicesclientmonthlyinvoice_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesclientmonthlyinvoice',
            name='month',
            field=models.DateField(blank=True, verbose_name='Месяц'),
        ),
    ]
