# Generated by Django 5.2 on 2025-05-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0014_alter_servicesclientmonthlyinvoice_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_add_ip',
        ),
        migrations.RemoveField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_add_nal',
        ),
        migrations.RemoveField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_add_ооо',
        ),
        migrations.RemoveField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_out_ip',
        ),
        migrations.RemoveField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_out_nal',
        ),
        migrations.RemoveField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_out_ооо',
        ),
    ]
