# Generated by Django 5.2 on 2025-05-15 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_remove_servicesclientmonthlyinvoice_operations_add_ip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_add_all',
        ),
        migrations.RemoveField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_add_diff_all',
        ),
        migrations.RemoveField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_out_all',
        ),
        migrations.RemoveField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_out_diff_all',
        ),
    ]
