# Generated by Django 5.2 on 2025-05-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0016_remove_servicesclientmonthlyinvoice_operations_add_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_add_all',
            field=models.FloatField(blank=True, default='0', null=True, verbose_name='Сумма прихода вся'),
        ),
        migrations.AddField(
            model_name='servicesclientmonthlyinvoice',
            name='operations_add_diff_all',
            field=models.FloatField(blank=True, default='0', null=True, verbose_name='Сумма прихода остаток'),
        ),
    ]
