# Generated by Django 5.2 on 2025-05-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_servicesclientmonthlyinvoice_operations_add_all_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name_long_ru',
            field=models.CharField(blank=True, max_length=266, null=True, verbose_name='Категории на русском полное название '),
        ),
    ]
