# Generated by Django 5.2 on 2025-06-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_service_name_long_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubcontractOtherCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название другого субподряда')),
            ],
            options={
                'verbose_name': 'Субподряд другое',
                'verbose_name_plural': 'Субподряд другое',
            },
        ),
    ]
