# Generated by Django 5.2 on 2025-06-06 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_alter_categnalog_in_page_nalog'),
        ('service', '0019_subcontractothercategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcontractothercategory',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bank.bank', verbose_name='банк'),
        ),
    ]
