# Generated by Django 5.2 on 2025-05-23 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogsError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Место ошибки')),
                ('info', models.CharField(blank=True, max_length=100000, null=True, verbose_name='Инфо о ошибке')),
            ],
            options={
                'verbose_name': 'Лог ошибок',
                'verbose_name_plural': 'Логи ошибок',
            },
        ),
        migrations.CreateModel(
            name='Logsinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Место ошибки')),
                ('info', models.CharField(blank=True, max_length=100000, null=True, verbose_name='Инфо о ошибке')),
            ],
            options={
                'verbose_name': 'Информационные сообщения',
                'verbose_name_plural': 'Информационные сообщения',
            },
        ),
    ]
