version: '3.7'
services:

  web:
    build: ./python/
    command: python manage.py runserver 0.0.0.0:3000
    volumes:
      - ../:/home/sites/Bookkeeping/
    ports:
      - 3000:3000
    # env_file:
    #   - ./.env

  celery:
    container_name: celery
    build: ./python/
    command: >
      sh -c "celery -A project worker -l info"
    volumes:
      - ../:/home/sites/Bookkeeping/
    ports:
      - "5566:5566"
    depends_on:
      - redis

  celery-beat:
    container_name: celery-beat
    build: ./python/
    command: >
      sh -c "celery -A project beat -l info"
    volumes:
      - ../:/home/sites/Bookkeeping/
    depends_on:
      - redis
      - celery

  redis:
    container_name: redis
    image: redis
    ports:
        - "6379:6379"    

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 89:8080

