# Generated by Django 5.2 on 2025-04-29 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_name_employee_first_name_employee_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='category',
        ),
    ]
