# Generated by Django 5.2 on 2025-04-30 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeincategory',
            options={'verbose_name': 'Отдел сотрудника', 'verbose_name_plural': 'Отделы сотрудников'},
        ),
    ]
