# Generated by Django 5.2 on 2025-05-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Банк', 'verbose_name_plural': 'Банки'},
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Банк'),
        ),
    ]
