# Generated by Django 5.2 on 2025-05-06 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_bank_options_alter_bank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeOperaccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Группа расходов операкаунта',
                'verbose_name_plural': 'Группы расходов операкаунта',
            },
        ),
    ]
