# Generated by Django 5.2 on 2025-05-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_groupeoperaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupeoperaccount',
            name='category',
            field=models.CharField(choices=[('Oфис', 'oper_account_office'), ('Реклама', 'oper_account_adv'), ('Прочее', 'oper_account_other'), ('Банковские расходы', 'oper_account_banking')], default='oper_account_other', max_length=20),
        ),
    ]
