# Generated by Django 5.2 on 2025-05-07 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0004_groupeoperaccount_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupeoperaccount',
            name='category',
            field=models.CharField(choices=[(1, 'Oфис'), (2, 'Реклама'), (3, 'Прочее'), (4, 'Банковские расходы')], default='oper_account_other', max_length=20),
        ),
        migrations.AlterField(
            model_name='groupeoperaccount',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя'),
        ),
    ]
