# Generated by Django 5.2 on 2025-05-07 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0005_alter_groupeoperaccount_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupeoperaccount',
            name='category',
            field=models.CharField(choices=[(1, 'Oфис'), (2, 'Реклама'), (3, 'Прочее'), (4, 'Банковские расходы')], default=1, max_length=20),
        ),
    ]
