# Generated by Django 5.2 on 2025-05-08 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_alter_groupeoperaccount_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupeSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank', verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Группа расходов зарплаты',
                'verbose_name_plural': 'Группы расходов зарплаты',
            },
        ),
    ]
