# Generated by Django 5.2 on 2025-05-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_groupesalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupesalary',
            name='article',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Очередность'),
        ),
    ]
