# Generated by Django 5.2 on 2025-05-29 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_groupesalary_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategNalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('article', models.PositiveIntegerField(blank=True, null=True, verbose_name='Очередность')),
                ('bank_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank', verbose_name='Банк')),
            ],
            options={
                'verbose_name': 'Категория налога',
                'verbose_name_plural': 'Категории налогов',
            },
        ),
    ]
