# Generated by Django 5.2 on 2025-06-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_categnalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='categnalog',
            name='in_page_nalog',
            field=models.BooleanField(default=True),
        ),
    ]
