# Generated by Django 5.2 on 2025-06-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_categnalog_in_page_nalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categnalog',
            name='in_page_nalog',
            field=models.BooleanField(default=True, verbose_name='Отображение на странице налогов'),
        ),
    ]
