# Generated by Django 5.2 on 2025-06-25 11:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0012_alter_categnalog_in_page_nalog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategForPercentGroupBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.bank', verbose_name='Банк')),
            ],
        ),
        migrations.CreateModel(
            name='CategPercentGroupBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('data', models.DateField(verbose_name='Дата добавления вручную')),
                ('percent', models.FloatField(default='0', verbose_name='Сумма')),
                ('is_auto_persent', models.BooleanField(default=True, verbose_name='Авто процент с прошлого месяца')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.categforpercentgroupbank', verbose_name='Категория')),
            ],
        ),
    ]
