# Generated by Django 5.2 on 2025-06-26 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_categforpercentgroupbank_categpercentgroupbank'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categforpercentgroupbank',
            options={'verbose_name': 'Категория процентных полей ', 'verbose_name_plural': 'Категории  процентных полей'},
        ),
        migrations.CreateModel(
            name='CategOperationsBetweenBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('bank_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='between_bank_in', to='bank.bank', verbose_name='банк откуда назначения операции')),
                ('bank_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='between_bank_to', to='bank.bank', verbose_name='банк конечный назначения операции')),
            ],
        ),
    ]
