# Generated by Django 5.2 on 2025-07-04 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0014_alter_categforpercentgroupbank_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoperationsbetweenbank',
            options={'verbose_name': 'Категория операций между банками', 'verbose_name_plural': 'Категория операций между банками'},
        ),
        migrations.AlterModelOptions(
            name='categpercentgroupbank',
            options={'verbose_name': 'Проценты для сумм по категориям', 'verbose_name_plural': 'Проценты для сумм по категориям'},
        ),
        migrations.AddField(
            model_name='categforpercentgroupbank',
            name='category_between',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.categoperationsbetweenbank', verbose_name='Категория операции между счетами'),
        ),
        migrations.AddField(
            model_name='categpercentgroupbank',
            name='category_between',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bank.categoperationsbetweenbank', verbose_name='Категория операции между счетами'),
        ),
        migrations.AddField(
            model_name='categpercentgroupbank',
            name='in_need_operations',
            field=models.BooleanField(default=True, verbose_name='Необходимость операции'),
        ),
    ]
