# Generated by Django 5.2 on 2025-08-06 13:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_alter_categoperationsbetweenbank_options_and_more'),
        ('employee', '0004_alter_employeeincategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления')),
                ('data', models.DateField(verbose_name='Дата добавления вручную')),
                ('percent', models.FloatField(default='0', verbose_name='Сумма')),
                ('is_auto_persent', models.BooleanField(default=True, verbose_name='Авто процент с прошлого месяца')),
                ('in_need_operations', models.BooleanField(default=True, verbose_name='Необходимость операции')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.categforpercentgroupbank', verbose_name='Категория')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Проценты для сумм по сотрудникам',
                'verbose_name_plural': 'Проценты для сумм по сотрудникам',
            },
        ),
    ]
